### ISSUE TITLE
Broken Dependencies for cairo-gobject 1.14.6-2.fc24

### ISSUE THREAD

**Issue by sadsfae** [drenninghoff/infinality-ultimate-fedora#15] opened 2016-08-03 13:09 UTC
I'm getting the follow error with dnf updates on Fedora24 now:

```
Skipping packages with broken dependencies:
 cairo-gobject                             i686           1.14.6-2.fc24           updates          30 k
 cairo-gobject                             x86_64         1.14.6-2.fc24           updates          30 k
```

Is this something I need to fix myself or could it be triggered by errata updates on deps for `cairo-gobject`?

Here's the cairo stuff I have installed:

```
python3-cairo-1.10.0-15.fc24.x86_64
cairo-infinality-ultimate-1.14.6-1.fc24.i686
cairomm-1.12.0-2.fc24.x86_64
cairo-infinality-ultimate-1.14.6-1.fc24.x86_64
pycairo-1.10.0-4.fc24.x86_64
cairo-gobject-1.14.6-1.fc24.x86_64
cairo-gobject-1.14.6-1.fc24.i686
```

Thanks for providing and working on these packages, they are great.

**Comment by genes1122** [comment] 2016-08-09 03:42
It looks like the problem is with infinality-ultimate-fedora.  These rpm commands show that it needs to provide a new version of cairo.

$ sudo rpm -q cairo-gobject --requires
...
cairo(x86-64) = 1.14.6-1.fc24
...
$ sudo rpm -q cairo-infinality-ultimate --provides
cairo = 1.14.6-1.fc24
...

Gene

**Comment by danielrenninghoff** [comment] 2016-08-09 05:47
Sorry about the delay. I was really busy :( I'm currently in the process of building the fixed packages, should be fixed in 30min.

**Comment by danielrenninghoff** [comment] 2016-08-09 06:37
Should be fixed now. Please install cairo-infinality-ultimate-gobject manually.

**Comment by sadsfae** [comment] 2016-08-10 08:32
Fixed for me, thank you @drenninghoff 

```
Upgrading:
 cairo-devel                                 x86_64                   1.14.6-2.fc24                    updates                               369 k
 cairo-gobject                               x86_64                   1.14.6-2.fc24                    updates                                30 k
 cairo-infinality-ultimate                   i686                     1.14.6-2.fc24                    infinality-ultimate                   739 k
 cairo-infinality-ultimate                   x86_64                   1.14.6-2.fc24                    infinality-ultimate                   706 k
```

Note, I replaced the system `cairo-gobject` with `cairo-infinality-ultimate-goject` after doing a standard dnf update via `dnf install cairo-infinality-ultimate-gobject --allowerasing`

I expect that's the best course of action?

**Comment by danielrenninghoff** [comment] 2016-08-10 08:42
Yes. It seems like there is no way to let dnf know to automatically install cairo-infinality-ultimate-\* packages instead of the regular ones.

**Closed as completed by danielrenninghoff** 2016-08-10 08:42 UTC
